### ISSUE TITLE
Suggestion: add tests and make it DRY

### ISSUE THREAD

**Issue by bsherman** [bhh32/ublue-it-cli#1]
I'm excited you are tackling this, and want to add a few suggestions from a wannabee rustacean (I've done some work in it, but don't call myself a pro) who also is enjoying and contributing a bit to the ublue-os project.

First, testing:
Cargo with rust makes it really easy to test and there's a lot of good examples. Of course there's the [official docs](https://doc.rust-lang.org/book/ch11-01-writing-tests.html) and I'm happy to share a [sample project](https://github.com/bsherman/notes2md) I wrote as an example of how I've tackled it (though I'm not saying it's the best way).

It's just so valuable to know functions do what you expect... especially if refactoring and trying to be DRY.  Also, the sooner you test, the easier to be in the habit of doing it, and then all your code will be tested from early on. Adding it later is very much a chore.

Second, DRY (don't repeat yourself):
You've got a good start here, but there's a lot of duplicated code. I think it could be cleaned nicely by creating some data structures (HashMaps or even arrays of tuples) which allow you to pull the different components of commands using the command line input as keys. Then you can have tests to verify you are building an array of strings which is the proper/expected command for a given set of CLI args, and only have one place you actually run a command. The confidence will be high that you are building all commands in a consistent manner and minimize some kinds of copy/paste bugs, etc.

Hope you find the suggestion useful.

**Comment by bhh32** [comment]
I appreciate your suggestions. I do plan on making some tests fairly soon. I'm also not a "pro" in Rust, so any suggestions are good ones. I think it's an interesting thought of creating an array of strings to run the command. I'll get with you on the Discord channel some time soon and go over your idea on how to do this. Also feel free to clone and do a PR if you'd like to contribute, I just request you make your own branch for changes so I can review them before they go into dev and then main.

**Comment by bhh32** [comment]
@bsherman I did quite a bit of refactoring that now builds up the command string based on the flags; as suggested. I'm still working out how to write the tests.

**Comment by bhh32** [comment]
@bsherman Refactoring and writing tests are complete! Thank you so much for the suggestions!
